#!/usr/bin/env python
"""One-command environment sync for the Data-Science-Project venv.

Keeps ALL requirements files current and in sync with the live environment:

  python requirements_sync.py            # regenerate BOTH tiers + full audit (offline, safe)
  python requirements_sync.py --check    # audit only, do not rewrite any file
  python requirements_sync.py --outdated # also list installable upgrades (needs network)

How it works (fully offline):
  1. Tier A - All-Rounder : reads the direct list in requirements.in, walks the
     dependency graph of the INSTALLED packages, and rewrites requirements.txt
     with the exact frozen closure (each package == its live installed version).
  2. Tier B - Windows Dev Kits : same walk from requirements-win_dev.in. Because
     both closures are computed from the same installation, shared packages can
     never diverge - no cross-file constraint needed.
  3. AUDIT : compares every installed package against both compiled files and
     prints live-version tables you can paste straight into DEPENDENCIES.md.

Because pins are derived from what is actually installed, the audit is always
clean after a run - a compile can never invent versions that are not present.
"""

from __future__ import annotations

import argparse
import importlib.metadata as md
import re
import subprocess
import sys
from collections import deque
from pathlib import Path

from packaging.markers import default_environment
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

ROOT = Path(__file__).resolve().parent
PY = str(sys.executable)
EXTRA_ENV = {**default_environment(), "extra": ""}

TIER_A_IN = ROOT / "requirements.in"
TIER_A_OUT = ROOT / "requirements.txt"
TIER_B_IN = ROOT / "requirements-win_dev.in"
TIER_B_OUT = ROOT / "requirements-win_dev.txt"

HEADER = "# This file is autogenerated by requirements_sync.py from the live .venv installation."
RUN_LINE = "# Run: .venv\\Scripts\\python.exe requirements_sync.py"


def norm(name: str) -> str:
    return canonicalize_name(name)


def read_direct(in_path: Path) -> list[Requirement]:
    reqs = []
    for ln in in_path.read_text(encoding="utf-8").splitlines():
        ln = ln.strip()
        if ln and not ln.startswith(("#", " ")):
            reqs.append(Requirement(ln))
    return reqs


def installed_index() -> dict[str, md.Distribution]:
    return {norm(d.metadata["Name"]): d for d in md.distributions()}


def deps_for(dist: md.Distribution, wanted_extras: frozenset[str]) -> list[Requirement]:
    """All base dependencies of `dist`, plus any extra-gated ones the wanted extras unlock."""
    out: list[Requirement] = []
    if dist is None or not dist.requires:
        return out
    for req_str in dist.requires:
        r = Requirement(req_str)
        if r.marker is None:
            out.append(r)
            continue
        for extra in (frozenset([""]) | wanted_extras):
            env = {**EXTRA_ENV, "extra": extra}
            if r.marker.evaluate(env):
                out.append(r)
                break
    return out


def tier_closure(direct: list[Requirement], installed: dict[str, md.Distribution], via_label: str) -> tuple[dict[str, tuple[frozenset[str], str]], set[str]]:
    """DFS the installed graph; returns {canonical: (extras, via)} per tier and missing set."""
    state: dict[str, tuple[frozenset[str], str]] = {}
    missing: set[str] = set()
    queue: deque[str] = deque()

    def add(key: str, extras: frozenset[str], via: str) -> bool:
        if key in missing:
            return False
        if installed.get(key) is None:
            missing.add(key)
            return False
        old = state.get(key)
        if old is None:
            state[key] = (extras, via)
            return True
        unioned = old[0] | extras
        if unioned != old[0]:
            state[key] = (unioned, old[1])
            return True
        return False

    for top in direct:
        key = norm(top.name)
        if add(key, frozenset(top.extras), via_label):
            queue.append(key)

    while queue:
        proj = queue.popleft()
        dist = installed[proj]
        for r in deps_for(dist, state[proj][0]):
            child = norm(r.name)
            if add(child, frozenset(r.extras or ()), proj):
                queue.append(child)
    return state, missing


def run(cmd: list[str]) -> None:
    print(f"\n$ {' '.join(cmd)}")
    subprocess.run(cmd, cwd=ROOT, check=True)


def compile_from_installed() -> None:
    run([PY, "-m", "pip", "check"])
    installed = installed_index()
    state_a, miss_a = tier_closure(read_direct(TIER_A_IN), installed, "requirements.in")
    state_b, miss_b = tier_closure(read_direct(TIER_B_IN), installed, "requirements-win_dev.in")

    def write_lines(state: dict[str, tuple[frozenset[str], str]]) -> list[str]:
        lines = []
        for key in sorted(state):
            extras, via = state[key]
            repr_name = key + ("[" + ",".join(sorted(extras)) + "]" if extras else "")
            ver = installed[key].version
            lines.append(f"{repr_name}=={ver}    # via {via}")
        return lines

    TIER_A_OUT.write_text("\n".join([HEADER, RUN_LINE, "", *write_lines(state_a), ""]), encoding="utf-8")
    TIER_B_OUT.write_text("\n".join([HEADER, RUN_LINE, "", *write_lines(state_b), ""]), encoding="utf-8")
    if miss_a or miss_b:
        print(f"\nWARNING: not installed (cannot pin): {sorted(miss_a | miss_b)}")


def parse_compiled(path: Path) -> list[str]:
    out = []
    for ln in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^([A-Za-z0-9_.\-]+)(?:\[[^\]]*\])?==", ln.strip())
        if m:
            out.append(norm(m.group(1)))
    return out


def table(title: str, direct: list[str], installed: dict[str, str], tier: str) -> None:
    print(f"\n## {title}")
    print("| Library | Live version | Tier |")
    print("| --- | --- | --- |")
    for name in direct:
        ver = installed.get(norm(name), "MISSING")
        print(f"| `{name}` | {ver} | {tier} |")


def audit() -> int:
    installed = {norm(d.metadata["Name"]): d.metadata["Version"] for d in md.distributions()}
    tier_a = set(parse_compiled(TIER_A_OUT))
    tier_b = set(parse_compiled(TIER_B_OUT))

    missing_required = (tier_a | tier_b) - set(installed)
    untracked = set(installed) - tier_a - tier_b

    print("\n=== ENVIRONMENT AUDIT ===")
    print(f"Installed packages : {len(installed)}")
    print(f"Required (A+B)     : {len(tier_a | tier_b)}")
    print(f"Required but NOT installed : {sorted(missing_required) or 'none'}")
    toolchain = sorted(untracked)
    print(f"Installed but UNPINNED (Tier C toolchain) : {', '.join(toolchain) or 'none'}")
    shared = sorted(tier_a & tier_b)
    print(f"Shared bottom layer (pinned in both files) : {', '.join(shared) or 'none'}")

    table("Tier A - Fundamental / All-Rounder (direct)", [r.name for r in read_direct(TIER_A_IN)], installed, "A")
    table("Tier B - Windows Dev Kits (direct)", [r.name for r in read_direct(TIER_B_IN)], installed, "B")

    ok = not missing_required
    print("\nAudit:", "CLEAN - requirements are in sync with the environment." if ok else "DRIFT DETECTED - see above.")
    return 0 if ok else 1


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync and audit project requirements (offline).")
    parser.add_argument("--check", action="store_true", help="audit only; do not rewrite compiled files")
    parser.add_argument("--outdated", action="store_true", help="also list installable upgrades (network)")
    args = parser.parse_args()

    if not args.check:
        compile_from_installed()

    code = audit()

    if args.outdated:
        run([PY, "-m", "pip", "list", "--outdated"])
    return code


if __name__ == "__main__":
    sys.exit(main())

