plugins {
    id 'java'
    id 'application'
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }
    test {
        java {
            srcDirs = ['tests']
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.3'
}

application {
    mainClass = 'Main'
}

tasks.named('test') {
    useJUnitPlatform()
}

run {
    standardInput = System.in
}